stages:
  - deploy

deploy-production:
  stage: deploy
  image: node:20
  tags:
    - docker
  only:
    - main
  script:
    - npm install -g @railway/cli@latest
    - echo "Token length is ${#RAILWAY_TOKEN}"
    - railway --version
    - railway up --detach --service testrail-mcp
  variables:
    RAILWAY_TOKEN: $RAILWAY_TOKEN
    RAILWAY_PROJECT_ID: 37a084fe-71f1-4e5f-906b-973d4f4bf022