stages:
  - deploy

deploy-production:
  stage: deploy
  image: node:20-alpine
  tags:
    - docker
  only:
    - main
  script:
    - npm install -g @railway/cli
    - railway link --project 37a084fe-71f1-4e5f-906b-973d4f4bf022 --environment production
    - railway up --detach
  variables:
    RAILWAY_TOKEN: $RAILWAY_TOKEN