include:
  - project: 'qa/scripts/aqa-ci-scripts'
    file: '/ci_aqa/pipelines/main.yml'

stages:
  - tag
  - build
  - deploy
  - sync

variables:
  PROJECT: "nebula"
  SERVICE_NAME: "testrail-mcp"
  ARGO_DEPLOY: "true"
  PROD_NAMESPACE: "obrio"
